accelerate launch --config_file=pipeline/accelerate_configs/accelerate_config_zero2.yaml \
    pipeline/train/instruction_following.py \
    --pretrained_model_name_or_path=/mnt/bn/ecom-govern-maxiangqian-lq/lj/OTTER-9B-INIT \
    --mimicit_path="/mnt/bn/ecom-govern-maxiangqian-lq/lj/data/dwq/FunQAf128_instructions_train.json" \
    --images_path="/mnt/bn/ecom-govern-maxiangqian-lq/lj/Otter/output/FunQA.json" \
    --train_config_path="/mnt/bn/ecom-govern-maxiangqian-lq/lj/data/dwq/FunQAf128_train_train.json" \
    --batch_size=16 \
    --num_epochs=2 \
    --report_to_wandb \
    --wandb_entity=ljunius \
    --run_name=otter9B_funqa \
    --wandb_project=MLLM \
    --workers=16 \
    --lr_scheduler=cosine \
    --learning_rate=1e-5 \
    --warmup_steps_ratio=0.01 \
    --save_ckpt_each_epoch \
    --gradient_checkpointing \
    --gradient_accumulation_steps=4 \
    --save_ckpt_each_epoch \
    --external_save_dir=/mnt/bn/ecom-govern-maxiangqian-lq/lj/Otter/exp_result \
    # --offline